const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
const BACKEND_URL = `${process.env.NEXT_PUBLIC_BACKEND_ENDPOINT}/api`;
const HUBSPOTBEARER = process.env.NEXT_PUBLIC_HUBSPOT_TOKEN

export { BASE_URL, BACKEND_URL, HUBSPOTBEARER };
